server:
  port: 8086

spring:
  application:
    name: zoonotic-disease-service
  datasource:
    url: jdbc:mysql://localhost:3306/zoonotic_db?createDatabaseIfNotExist=true
    username: ${MYSQL_APP_USER:dpdms}
    password: ${MYSQL_APP_PASSWORD:dpdms_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
